/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartLinkIdRouteImport } from './routes/start.$linkId'
import { Route as AdminConfigRouteImport } from './routes/admin.config'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartLinkIdRoute = StartLinkIdRouteImport.update({
  id: '/start/$linkId',
  path: '/start/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/config': typeof AdminConfigRoute
  '/start/$linkId': typeof StartLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/config': typeof AdminConfigRoute
  '/start/$linkId': typeof StartLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/config': typeof AdminConfigRoute
  '/start/$linkId': typeof StartLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/config' | '/start/$linkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/config' | '/start/$linkId'
  id: '__root__' | '/' | '/admin' | '/admin/config' | '/start/$linkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StartLinkIdRoute: typeof StartLinkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/$linkId': {
      id: '/start/$linkId'
      path: '/start/$linkId'
      fullPath: '/start/$linkId'
      preLoaderRoute: typeof StartLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfigRoute: typeof AdminConfigRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfigRoute: AdminConfigRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StartLinkIdRoute: StartLinkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
